// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_AR_SCREEN_H
#define UI_AR_SCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Ar_Screen
extern void ui_Ar_Screen_screen_init(void);
extern void ui_Ar_Screen_screen_destroy(void);
extern lv_obj_t * ui_Ar_Screen;
extern lv_obj_t * ui_Humidade_Ar;
extern lv_obj_t * ui_Arc_Humidade_Ar;
extern lv_obj_t * ui_Bar_Temp;
extern lv_obj_t * ui_Temp_Ar;
extern lv_obj_t * ui_Label2;
extern lv_obj_t * ui_Label5;
extern lv_obj_t * ui_Label7;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

