// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

lv_obj_t * ui_Ar_Screen = NULL;
lv_obj_t * ui_HumidadeAr = NULL;
lv_obj_t * ui_TempAr = NULL;
// event funtions

// build funtions

void ui_Ar_Screen_screen_init(void)
{
    ui_Ar_Screen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Ar_Screen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_HumidadeAr = lv_label_create(ui_Ar_Screen);
    lv_obj_set_width(ui_HumidadeAr, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_HumidadeAr, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_HumidadeAr, 2);
    lv_obj_set_y(ui_HumidadeAr, -35);
    lv_obj_set_align(ui_HumidadeAr, LV_ALIGN_CENTER);

    ui_TempAr = lv_label_create(ui_Ar_Screen);
    lv_obj_set_width(ui_TempAr, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TempAr, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_TempAr, LV_ALIGN_CENTER);

}

void ui_Ar_Screen_screen_destroy(void)
{
    if(ui_Ar_Screen) lv_obj_del(ui_Ar_Screen);

    // NULL screen variables
    ui_Ar_Screen = NULL;
    ui_HumidadeAr = NULL;
    ui_TempAr = NULL;

}
