// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

lv_obj_t * ui_Def_Screen = NULL;
lv_obj_t * ui_Roller2 = NULL;
// event funtions

// build funtions

void ui_Def_Screen_screen_init(void)
{
    ui_Def_Screen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Def_Screen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_img_src(ui_Def_Screen, &ui_img_gemini_generated_image_fo8hn8fo8hn8fo8h_129x160_png,
                                LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Roller2 = lv_roller_create(ui_Def_Screen);
    lv_roller_set_options(ui_Roller2, "Option 1\nOption 2\nOption 3", LV_ROLLER_MODE_NORMAL);
    lv_obj_set_height(ui_Roller2, 159);
    lv_obj_set_width(ui_Roller2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_align(ui_Roller2, LV_ALIGN_CENTER);

    lv_obj_set_style_blend_mode(ui_Roller2, LV_BLEND_MODE_NORMAL, LV_PART_SELECTED | LV_STATE_DEFAULT);

}

void ui_Def_Screen_screen_destroy(void)
{
    if(ui_Def_Screen) lv_obj_del(ui_Def_Screen);

    // NULL screen variables
    ui_Def_Screen = NULL;
    ui_Roller2 = NULL;

}
