// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

lv_obj_t * ui_Def_Screen = NULL;
lv_obj_t * ui_Label1 = NULL;
// event funtions

// build funtions

void ui_Def_Screen_screen_init(void)
{
    ui_Def_Screen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Def_Screen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label1 = lv_label_create(ui_Def_Screen);
    lv_obj_set_width(ui_Label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label1, LV_ALIGN_CENTER);

}

void ui_Def_Screen_screen_destroy(void)
{
    if(ui_Def_Screen) lv_obj_del(ui_Def_Screen);

    // NULL screen variables
    ui_Def_Screen = NULL;
    ui_Label1 = NULL;

}
