// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_HOME_SCREEN_H
#define UI_HOME_SCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Home_Screen
extern void ui_Home_Screen_screen_init(void);
extern void ui_Home_Screen_screen_destroy(void);
extern lv_obj_t * ui_Home_Screen;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

