// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

lv_obj_t * ui_Humidade_Solo_Screen = NULL;
lv_obj_t * ui_HumidadeSolo = NULL;
// event funtions

// build funtions

void ui_Humidade_Solo_Screen_screen_init(void)
{
    ui_Humidade_Solo_Screen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Humidade_Solo_Screen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_HumidadeSolo = lv_label_create(ui_Humidade_Solo_Screen);
    lv_obj_set_width(ui_HumidadeSolo, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_HumidadeSolo, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_HumidadeSolo, LV_ALIGN_CENTER);

}

void ui_Humidade_Solo_Screen_screen_destroy(void)
{
    if(ui_Humidade_Solo_Screen) lv_obj_del(ui_Humidade_Solo_Screen);

    // NULL screen variables
    ui_Humidade_Solo_Screen = NULL;
    ui_HumidadeSolo = NULL;

}
