// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_HOME_SCREEN_H
#define UI_HOME_SCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Home_Screen
extern void ui_Home_Screen_screen_init(void);
extern void ui_Home_Screen_screen_destroy(void);
extern lv_obj_t * ui_Home_Screen;
extern lv_obj_t * ui_Image1;
extern lv_obj_t * ui_Label11;
extern lv_obj_t * ui_Nivel_Agua;
extern lv_obj_t * ui_Connection_Image;
extern lv_obj_t * ui_Connection_Text;
extern lv_obj_t * ui_No_Connection_Image;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

