// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_LUMINOSIDADE_DEF_H
#define UI_LUMINOSIDADE_DEF_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Luminosidade_Def
extern void ui_Luminosidade_Def_screen_init(void);
extern void ui_Luminosidade_Def_screen_destroy(void);
extern lv_obj_t * ui_Luminosidade_Def;
extern lv_obj_t * ui_Label10;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

