// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_SOLO_SCREEN1_H
#define UI_SOLO_SCREEN1_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Solo_Screen1
extern void ui_Solo_Screen1_screen_init(void);
extern void ui_Solo_Screen1_screen_destroy(void);
extern lv_obj_t * ui_Solo_Screen1;
extern lv_obj_t * ui_ArcHumidadeSolo1;
extern lv_obj_t * ui_Label1;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

