// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

lv_obj_t * ui_Solo_Screen1 = NULL;
lv_obj_t * ui_ArcHumidadeSolo1 = NULL;
lv_obj_t * ui_Label1 = NULL;
// event funtions

// build funtions

void ui_Solo_Screen1_screen_init(void)
{
    ui_Solo_Screen1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Solo_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_img_src(ui_Solo_Screen1, &ui_img_gemini_generated_image_fo8hn8fo8hn8fo8h_129x160_png,
                                LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ArcHumidadeSolo1 = lv_arc_create(ui_Solo_Screen1);
    lv_obj_set_width(ui_ArcHumidadeSolo1, 112);
    lv_obj_set_height(ui_ArcHumidadeSolo1, 118);
    lv_obj_set_x(ui_ArcHumidadeSolo1, 0);
    lv_obj_set_y(ui_ArcHumidadeSolo1, 17);
    lv_obj_set_align(ui_ArcHumidadeSolo1, LV_ALIGN_CENTER);
    lv_arc_set_value(ui_ArcHumidadeSolo1, 50);
    lv_obj_set_style_opa(ui_ArcHumidadeSolo1, 200, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_color(ui_ArcHumidadeSolo1, lv_color_hex(0x5CE0F6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_ArcHumidadeSolo1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_color(ui_ArcHumidadeSolo1, lv_color_hex(0x6565ED), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_ArcHumidadeSolo1, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_ArcHumidadeSolo1, lv_color_hex(0x133AE6), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ArcHumidadeSolo1, 255, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_Label1 = lv_label_create(ui_Solo_Screen1);
    lv_obj_set_width(ui_Label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label1, 0);
    lv_obj_set_y(ui_Label1, -64);
    lv_obj_set_align(ui_Label1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label1, "Mudar Humidade\nDesejada");
    lv_obj_set_style_text_color(ui_Label1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Label1, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Label1, lv_color_hex(0x1E9F36), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Label1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_Label1, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);

}

void ui_Solo_Screen1_screen_destroy(void)
{
    if(ui_Solo_Screen1) lv_obj_del(ui_Solo_Screen1);

    // NULL screen variables
    ui_Solo_Screen1 = NULL;
    ui_ArcHumidadeSolo1 = NULL;
    ui_Label1 = NULL;

}
