// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

lv_obj_t * ui_Sistema_Screen = NULL;
// event funtions

// build funtions

void ui_Sistema_Screen_screen_init(void)
{
    ui_Sistema_Screen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Sistema_Screen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_img_src(ui_Sistema_Screen, &ui_img_gemini_generated_image_fo8hn8fo8hn8fo8h_129x160_png,
                                LV_PART_MAIN | LV_STATE_DEFAULT);

}

void ui_Sistema_Screen_screen_destroy(void)
{
    if(ui_Sistema_Screen) lv_obj_del(ui_Sistema_Screen);

    // NULL screen variables
    ui_Sistema_Screen = NULL;

}
