// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_TEMP_DEF_SCREEN_H
#define UI_TEMP_DEF_SCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Temp_Def_Screen
extern void ui_Temp_Def_Screen_screen_init(void);
extern void ui_Temp_Def_Screen_screen_destroy(void);
extern lv_obj_t * ui_Temp_Def_Screen;
extern lv_obj_t * ui_Arc_Def_Temp;
extern lv_obj_t * ui_Label8;
extern lv_obj_t * ui_Temp_Desired;
extern lv_obj_t * ui_Label4;
extern lv_obj_t * ui_Label12;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

