// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

lv_obj_t * ui_Temp_Def_Screen = NULL;
lv_obj_t * ui_Arc_Def_Temp = NULL;
lv_obj_t * ui_Label8 = NULL;
lv_obj_t * ui_Temp_Desired = NULL;
// event funtions

// build funtions

void ui_Temp_Def_Screen_screen_init(void)
{
    ui_Temp_Def_Screen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Temp_Def_Screen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_img_src(ui_Temp_Def_Screen, &ui_img_gemini_generated_image_fo8hn8fo8hn8fo8h_129x160_png,
                                LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Arc_Def_Temp = lv_arc_create(ui_Temp_Def_Screen);
    lv_obj_set_width(ui_Arc_Def_Temp, 112);
    lv_obj_set_height(ui_Arc_Def_Temp, 118);
    lv_obj_set_x(ui_Arc_Def_Temp, 1);
    lv_obj_set_y(ui_Arc_Def_Temp, 17);
    lv_obj_set_align(ui_Arc_Def_Temp, LV_ALIGN_CENTER);
    lv_arc_set_value(ui_Arc_Def_Temp, 50);
    lv_obj_set_style_arc_color(ui_Arc_Def_Temp, lv_color_hex(0x5CE0F6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_Arc_Def_Temp, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_color(ui_Arc_Def_Temp, lv_color_hex(0x6565ED), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_Arc_Def_Temp, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_Arc_Def_Temp, lv_color_hex(0x133AE6), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Arc_Def_Temp, 255, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_Label8 = lv_label_create(ui_Temp_Def_Screen);
    lv_obj_set_width(ui_Label8, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label8, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label8, 0);
    lv_obj_set_y(ui_Label8, -64);
    lv_obj_set_align(ui_Label8, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label8, "Mudar Temp\nDesejada");
    lv_obj_set_style_text_color(ui_Label8, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label8, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Label8, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label8, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Label8, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Label8, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_Label8, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Temp_Desired = lv_label_create(ui_Temp_Def_Screen);
    lv_obj_set_width(ui_Temp_Desired, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Temp_Desired, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Temp_Desired, LV_ALIGN_CENTER);
    lv_obj_set_style_text_color(ui_Temp_Desired, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Temp_Desired, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

}

void ui_Temp_Def_Screen_screen_destroy(void)
{
    if(ui_Temp_Def_Screen) lv_obj_del(ui_Temp_Def_Screen);

    // NULL screen variables
    ui_Temp_Def_Screen = NULL;
    ui_Arc_Def_Temp = NULL;
    ui_Label8 = NULL;
    ui_Temp_Desired = NULL;

}
